name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js & npm
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Run Build Script
        run: npm run build
      - name: Run Tests
        run: npm run test:ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest Tests
          path: junit.xml
          reporter: jest-junit
