name: build
on:
  push:
    branches:
      - main
      - feature/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js & npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Run Build Script
        run: npm run build
